#main-resources

marca = "MORENO", "SPECIALIZED", "SCOTT", "TREK", "GIANT", "CANYON", "CANNONDALE", "ORBEA", "BMC", "PINARELLO", "BIANCHI"

tipo = "MONTANIA", "PASEO", "COMPETICION", "EXPOSICION", "ENTRENAMIENTO"

rodado = "XS", "S", "M", "M2"

color = "ROJO", "VERDE", "AZUL", "AMARILLO", "NEGRO", "BLANCO"